<a href="https://colab.research.google.com/github/Tony-47/training/blob/main/Tonyyy_47.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def functionname( parameter):
    block of code
    return output

SyntaxError: invalid syntax (<ipython-input-6-d0104cd3636e>, line 2)

In [ ]:
def calArea(r):
    a=3.14*r*r
    return a

In [ ]:
calArea(r=10)

314.0

In [ ]:
w=calArea(r=23)
w

1661.06

In [ ]:
type(w)
w+10

1671.06

In [ ]:
a=print('india')
a

india


In [ ]:
def aor(l,w):
    area=l*w
    return area

In [ ]:
aor(w=10,l=5)

50

In [ ]:
aor(10,5)

50

In [ ]:
aor(l=10,w=5)

50

In [ ]:
def area(rad,length,width):
    aoc=3.14*rad*rad
    aor= length*width
    return aoc,aor

In [ ]:
area(rad=10,length=20,width=5)

(314.0, 100)

In [ ]:
def area(rad,length,width):
    aoc=3.14*rad*rad
    aor= length*width
    return aoc,aor
    return {'Area of circle':aoc,'Area of rectangle':aor}

In [ ]:
a=area(rad=15,length=30,width=10)

In [ ]:
a['Area of rectangle']

TypeError: tuple indices must be integers or slices, not str

In [ ]:
t='HydrabAAd  500008 Telangana'
t

'HydrabAAd  500008 Telangana'

In [ ]:
def countA(x):
  d=x.lower()
  return d.count('a')

In [ ]:
countA(t)

6

In [ ]:
def count_num_alpha(x):
    c=0
    d=0
    for i in x:
        if i.isalpha():
            c+=1
        elif i.isnumeric():
            d+=1
    return {'Number of alphabets':c,'NUmber of digits':d}


In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(30,99,15)
a

array([63, 86, 54, 37, 79, 55, 52, 50, 40, 96, 81, 44, 78, 44, 71])

In [ ]:
b = np.random.randint(45,46,(8,9))
b

array([[45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45]])

In [ ]:
b.shape

(8, 9)

In [ ]:
b.ndim

2

In [ ]:
b[7,0]

45

In [ ]:
b[2:6]

array([[45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45, 45, 45]])

In [ ]:
import pandas as pd

In [ ]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [ ]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [ ]:
t.shape

(4, 2)

In [ ]:
t.ndim

2

In [ ]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [ ]:
df=pd.DataFrame(t,columns=['Tony','boii'],index=[289,290,291,292])
df

Tony  boii
289     4     7
290     2     9
291     7     3
292    90    50

In [ ]:
df.columns

Index(['Tony', 'boii'], dtype='object')

In [ ]:
df['boii']

289     7
290     9
291     3
292    50
Name: boii, dtype: int64

In [ ]:
df['boii'].std()

21.975364995072702

In [ ]:
df['boii'].min()

3

In [ ]:
df['boii'].max()

50

In [ ]:
df['boii'].quantile(0.25)

6.0

In [ ]:
df['boii'].quantile(0.75)

19.25

In [ ]:
df['boii'].mean()

17.25

In [ ]:
df['boii'].median()

8.0

In [ ]:
df['boii'].mode()

0     3
1     7
2     9
3    50
Name: boii, dtype: int64